### ISSUE TITLE
[BUG] Command permissions and message related issue.

### ISSUE THREAD

**Issue by TUCAOEVER** [Ghost-chu/QuickShop-Reremake#881] opened 2021-03-20 03:40 UTC
### Describe the bug:
1.I tried to disable preview feature, which related to " /qs silentpreview" command, by using permission, but the preview permission seems given by default in plugin.yml, and if i changed the plugin.yml file, all system will broke. I was told that "Okay yeah as far as I can tell, it doesn't actually check if you have the permission quickshop.preview"
said by Starmism, one of the developers.So i thought u might already known what is going on.
2.An interesting issue, which i found during my editing "messages.json", it's about the line of "player-sold-to-your-store", if i don't add any characters behind "{2}", the output message would shown like this
![image](https://user-images.githubusercontent.com/43756134/111858045-ccc90280-8970-11eb-9f1c-686dd2728616.png)

**Comment by sandtechnology** [comment] 2021-03-20 12:38
I have check the code, `quickshop.preview` permission will be check, could you reproduce in debug mode (/qs debug) and then provide the paste by /qs paste?

**Comment by Starmism** [comment] 2021-03-20 12:51
Upon further examination, it does seem that the `quickshop.preview` permission is checked, just not where I thought. Though while testing, I did have a hard time negating the permission since it is inherently true for all players. Are you using LuckPerms? If so, you can't negate a permission by putting a dash in front of it such as `-quickshop.preview`. You must set it to false explicitly, like `/lp group member permission set quickshop.preview false`.

**Comment by TUCAOEVER** [comment] 2021-03-20 13:01
> Upon further examination, it does seem that the `quickshop.preview` permission is checked, just not where I thought. Though while testing, I did have a hard time negating the permission since it is inherently true for all players. Are you using LuckPerms? If so, you can't negate a permission by putting a dash in front of it such as `-quickshop.preview`. You must set it to false explicitly, like `/lp group member permission set quickshop.preview false`.

That works. Thx. What about the other issue?

**Comment by Starmism** [comment] 2021-03-20 14:14
Okay so the second issue is caused by the way the language data is parsed by the plugin. If it successfully gets an ItemStack, it converts it into JSON format and slaps those ####### around it so the parser knows that it has a real ItemStack in it. Right now, it can only work if there's specific number of things around it and those are in the perfect order, so that won't be fixed until someone rewrites how the parser parses stuff, which could definitely be done, but is also definitely not high on anyone's priority list. I'll let you know if it gets fixed soon though!

**Comment by Ghost-chu** [comment] 2021-03-20 15:22
> Upon further examination, it does seem that the `quickshop.preview` permission is checked, just not where I thought. Though while testing, I did have a hard time negating the permission since it is inherently true for all players. Are you using LuckPerms? If so, you can't negate a permission by putting a dash in front of it such as `-quickshop.preview`. You must set it to false explicitly, like `/lp group member permission set quickshop.preview false`.

https://github.com/Ghost-chu/QuickShop-Reremake/blob/a2a409848dc7914af6bca54ae28b771ff258dfb9/src/main/java/org/maxgamer/quickshop/command/CommandManager.java#L169

https://github.com/Ghost-chu/QuickShop-Reremake/blob/a2a409848dc7914af6bca54ae28b771ff258dfb9/src/main/java/org/maxgamer/quickshop/command/CommandManager.java#L406

**Closed** 2021-04-05 08:55 UTC
Labels: Bug, Priority：Minor
