### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by tyrantkoala** [Ghost-chu/QuickShop-Reremake#481] opened 2020-06-09 19:54 UTC
**Describe the bug**
It Crashes my server after like 5min

**Expected behavior**
Happened Randomly

Here is console:
09.06 15:52:13 [Server] WARN [QuickShop] Plugin QuickShop v4.0.2.12 generated an exception while executing task 15181
09.06 15:52:13 [Server] INFO java.lang.IllegalStateException: Asynchronous ChunkMapDistance::addTicket!
09.06 15:52:13 [Server] INFO at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[patched_1.15.2.jar:git-Paper-345]
09.06 15:52:13 [Server] INFO at net.minecraft.server.v1_15_R1.ChunkMapDistance.addTicket(ChunkMapDistance.java:158) ~[patched_1.15.2.jar:git-Paper-345]
09.06 15:52:13 [Server] INFO at net.minecraft.server.v1_15_R1.ChunkMapDistance.addTicket(ChunkMapDistance.java:311) ~[patched_1.15.2.jar:git-Paper-345]
09.06 15:52:13 [Server] INFO at net.minecraft.server.v1_15_R1.ChunkProviderServer.addTicket(ChunkProviderServer.java:958) ~[patched_1.15.2.jar:git-Paper-345]
09.06 15:52:13 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.CraftWorld.getChunkAt(CraftWorld.java:402) ~[patched_1.15.2.jar:git-Paper-345]
09.06 15:52:13 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.CraftWorld.getChunkAt(CraftWorld.java:1016) ~[patched_1.15.2.jar:git-Paper-345]
09.06 15:52:13 [Server] INFO at org.bukkit.Location.getChunk(Location.java:123) ~[patched_1.15.2.jar:git-Paper-345]

**Comment by quiquelhappy** [comment] 2020-06-09 21:26
duplicate of: [https://github.com/Ghost-chu/QuickShop-Reremake/issues/480](https://github.com/Ghost-chu/QuickShop-Reremake/issues/480)

**Closed** 2020-06-10 00:48 UTC
Labels: Bug, Duplicate

**Comment by sandtechnology** [comment] 2020-06-10 01:01
Please try the newest version https://www.spigotmc.org/resources/quickshop-reremake-1-15-ready-bees-bees-bee.62575/download?version=336474
