### ISSUE TITLE
Could not pass event InventoryCloseEvent to QuickShop vReremake 1.3.0

### ISSUE THREAD

**Issue by Fabrimat** [Ghost-chu/QuickShop-Reremake#22] opened 2018-11-10 16:06 UTC
QuickShop vReremake 1.3.0
Spigot 1.13.1

`[Server thread/ERROR]: Could not pass event InventoryCloseEvent to QuickShop vReremake 1.3.0
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[server.jar:git-Spigot-f6a273b-a639ae4]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-f6a273b-a639ae4]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[server.jar:git-Spigot-f6a273b-a639ae4]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[server.jar:git-Spigot-f6a273b-a639ae4]
	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:905) ~[server.jar:git-Spigot-f6a273b-a639ae4]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1922) ~[server.jar:git-Spigot-f6a273b-a639ae4]
	at net.minecraft.server.v1_13_R2.PacketPlayInCloseWindow.a(PacketPlayInCloseWindow.java:18) ~[server.jar:git-Spigot-f6a273b-a639ae4]
	at net.minecraft.server.v1_13_R2.PacketPlayInCloseWindow.a(PacketPlayInCloseWindow.java:1) ~[server.jar:git-Spigot-f6a273b-a639ae4]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[server.jar:git-Spigot-f6a273b-a639ae4]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [server.jar:git-Spigot-f6a273b-a639ae4]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [server.jar:git-Spigot-f6a273b-a639ae4]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [server.jar:git-Spigot-f6a273b-a639ae4]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [server.jar:git-Spigot-f6a273b-a639ae4]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [server.jar:git-Spigot-f6a273b-a639ae4]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
	at net.minecraft.server.v1_13_R2.InventoryEnderChest.getLocation(InventoryEnderChest.java:18) ~[server.jar:git-Spigot-f6a273b-a639ae4]
	at org.bukkit.craftbukkit.v1_13_R2.inventory.CraftInventory.getLocation(CraftInventory.java:488) ~[server.jar:git-Spigot-f6a273b-a639ae4]
	at org.maxgamer.quickshop.Listeners.PlayerListener.invCloseEvent(PlayerListener.java:376) ~[QuickShop-Reremake.1.3.0.jar:?]
	at sun.reflect.GeneratedMethodAccessor420.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[server.jar:git-Spigot-f6a273b-a639ae4]
	... 16 more`

**Comment by Gerlif** [comment] 2018-11-11 23:54
Getting the same error:

`10.11 01:50:44 [Server] ERROR Could not pass event InventoryCloseEvent to QuickShop vReremake 1.3.0
10.11 01:50:44 [Server] INFO org.bukkit.event.EventException: null
10.11 01:50:44 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
10.11 01:50:44 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
10.11 01:50:44 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
10.11 01:50:44 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
10.11 01:50:44 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:963) ~[spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
10.11 01:50:44 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1924) ~[spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
10.11 01:50:44 [Server] INFO at net.minecraft.server.v1_13_R2.PacketPlayInCloseWindow.a(PacketPlayInCloseWindow.java:18) ~[spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
10.11 01:50:44 [Server] INFO at net.minecraft.server.v1_13_R2.PacketPlayInCloseWindow.a(PacketPlayInCloseWindow.java:1) ~[spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
10.11 01:50:44 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
10.11 01:50:44 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_181]
10.11 01:50:44 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_181]
10.11 01:50:44 [Server] INFO at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
10.11 01:50:44 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
10.11 01:50:44 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
10.11 01:50:44 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
10.11 01:50:44 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
10.11 01:50:44 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
10.11 01:50:44 [Server] INFO Caused by: java.lang.NullPointerException
10.11 01:50:44 [Server] INFO at org.maxgamer.quickshop.Shop.ShopManager.getShop(ShopManager.java:143) ~[?:?]
10.11 01:50:44 [Server] INFO at org.maxgamer.quickshop.Listeners.PlayerListener.invCloseEvent(PlayerListener.java:377) ~[?:?]
10.11 01:50:44 [Server] INFO at sun.reflect.GeneratedMethodAccessor283.invoke(Unknown Source) ~[?:?]
10.11 01:50:44 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
10.11 01:50:44 [Server] INFO at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_181]
10.11 01:50:44 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
10.11 01:50:44 [Server] INFO ... 16 more`

**Comment by arboriginal** [comment] 2018-11-12 16:21
Same for me, QuickShop vReremake 1.3.0 & Spigot 1.13.2.

It happens when I open a chest (not everytime) but the plugin goes on to work.

**Comment by ecoterrorist** [comment] 2018-11-12 17:58
I can confirm this is happening

**Comment by Ghost-chu** [comment] 2018-11-16 08:16
Thanks for reporting, fix in next version.

**Comment by Ghost-chu** [comment] 2018-11-16 09:46
Fixed in 1.3.0.1

**Comment by Ghost-chu** [comment] 2018-11-16 09:46
Fixed in 1.3.0.1

**Closed by Ghost-chu** 2018-11-16 09:46 UTC
